from mongoengine.document import Document
from mongoengine.fields import BooleanField, DateTimeField, IntField, ReferenceField, StringField

from server.db.player import Player


class Hero(Document):
    name = StringField(required=True)
    release_date = DateTimeField()
    blizz_role = StringField()
    can_tank = BooleanField(default=False)
    can_solo_heal = BooleanField(default=False)
    can_heal_ally = BooleanField(default=False)
    can_heal_self = BooleanField(default=False)
    can_shield_self = BooleanField(default=False)
    can_shield_ally = BooleanField(default=False)
    can_solo_lane = BooleanField(default=False)
    has_aoe_heal = BooleanField(default=False)
    has_dot_heal = BooleanField(default=False)
    has_percent_heal = BooleanField(default=False)
    has_aoe_damage = BooleanField(default=False)
    has_dot_damage = BooleanField(default=False)
    has_percent_damage = BooleanField(default=False)
    has_waveclear = BooleanField(default=False)
    has_global = BooleanField(default=False)
    has_stun = BooleanField(default=False)
    has_root = BooleanField(default=False)
    has_slow = BooleanField(default=False)
    has_silence = BooleanField(default=False)
    has_blind = BooleanField(default=False)
    has_sleep = BooleanField(default=False)
    has_polymorph = BooleanField(default=False)
    has_knockback = BooleanField(default=False)
    has_stasis = BooleanField(default=False)
    has_time_stop = BooleanField(default=False)
    has_parry = BooleanField(default=False)
    has_unrevealable = BooleanField(default=False)
    has_reveal = BooleanField(default=False)
    has_stealth_self = BooleanField(default=False)
    has_stealth_ally = BooleanField(default=False)
    has_evade_self = BooleanField(default=False)
    has_evade_ally = BooleanField(default=False)
    has_unstoppable_self = BooleanField(default=False)
    has_unstoppable_ally = BooleanField(default=False)
    has_protected_self = BooleanField(default=False)
    has_protected_ally = BooleanField(default=False)
    has_unkillable_self = BooleanField(default=False)
    has_unkillable_ally = BooleanField(default=False)
    has_invulnerable_self = BooleanField(default=False)
    has_invulnerable_ally = BooleanField(default=False)
    has_aa_speedup_ally = BooleanField(default=False)
    has_aa_speedup_self = BooleanField(default=False)
    has_move_speedup_ally = BooleanField(default=False)
    has_move_speedup_self = BooleanField(default=False)
    has_aa_dpsup_ally = BooleanField(default=False)
    has_aa_dpsup_self = BooleanField(default=False)
    has_crits_ally = BooleanField(default=False)
    has_crits_self = BooleanField(default=False)
    has_ability_dpsup_ally = BooleanField(default=False)
    has_ability_dpsup_self = BooleanField(default=False)


class PlayerHero(Document):
    player = ReferenceField(Player, required=True)
    hero = ReferenceField(Hero, required=True)
    mode = StringField(required=True)
    level = IntField(required=True, default=1)
    games_played = IntField(required=True, default=0)
    games_won = IntField(required=True, default=0)

    def __repr__(self):
        data_dict = {'level': self.level, 'games_played': self.games_played, 'games_won': self.games_won}
        return '{}: {}'.format(self.hero.name, data_dict)
